version: 2
project_name: steampipe-plugin-proxmox

before:
  hooks:
    - go mod tidy

builds:
  - id: proxmox
    binary: steampipe-plugin-proxmox.plugin
    main: .
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: proxmox
    builds:
      - proxmox
    format: gzip
    name_template: "{{ .ProjectName }}.{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: becash143
    name: steampipe-plugin-proxmox

changelog:
  sort: asc
